language: python
python:
  - "3.6.4"
# command to install dependencies
install: "pip install -r requirements-dev.txt"
# command to run tests
script:
  - flake8 jadlog.py
  - pytest tests/
#  - py.test --cov=pytocli tests/
#  - python -m doctest README.md
# after_success:
#  - coveralls