language: python
python:
  - "3.8-dev"
# command to install dependencies
install:
  - cp contrib/env-sample .env
  - pip install -r requirements-dev.txt codecov
# command to run tests
script:
  - flake8 .
  - pycodestyle .
  - coverage run -m pytest -v --doctest-glob='*.md'
#  - python -m doctest README.md jadlog/*.py -v
after_success:
  - codecov