name: Python application

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt codecov
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Pycodestyle
      run: |
        pycodestyle .
    - name: Test with coverage
      run: |
        coverage run -m pytest -v --doctest-glob='*.md'
    - name: Posting Coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        codecov
